#設定参考　https://tech.actindi.net/2019/10/11/090521

# アクション名
name: lint, typecheck, test

# タイミングを指定
on: push

jobs:
  lint-typecheck-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Set up Environments
        run: |
          cat > .env <<EOF
          TEST=${{ secrets.TOKEN }}
          EOF
          cat .env
          ls
